fix: apply timezone in logger
gram-js/gramjs pull request #319
Opened 2022-05-12 17:37 UTC by MohamadKh75

fix https://github.com/gram-js/gramjs/issues/317

2022-05-12 17:41 UTC, painor commented
Looks good but I have a couple of concerns.

I don't see the need for calculating `const tzOffset = new Date().getTimezoneOffset() * 60000;` each time.
maybe this can be done once in the constructor? 

Can we maybe put the date calculation in a separate function in the logger, maybe getDate() and call that in the format() method.
That way if someone wanted to override the getDate method they can do so.

2022-05-12 17:50 UTC, MohamadKh75 commented
Updated @painor

2022-05-12 18:43 UTC, painor requested changes

2022-05-13 12:16 UTC, MohamadKh75 commented
Updated @painor

2022-05-13 12:34 UTC, painor approved these changes

2022-05-13 12:34 UTC, merged